services:
  back:
    build: .
    image: armitage1/lanrumble-django
    restart: always
    command: daphne -e ssl:8000:privateKey=ca.key:certKey=ca.crt lanrumble.asgi:application
    depends_on:
      - db
    ports:
      - 8000:8000
    volumes:
      - media:/app/jeux/media
      - /tmp/app/django_db_socket:/run/postgresd
      - logs:/var/log/
    secrets:
      - source: crt
        target: /app/ca.crt
      - source: key
        target: /app/ca.key
    environment:
      SECRET_KEY : ${SECRET_KEY}
      EMAIL_HOST_PASSWORD : ${EMAIL_HOST_PASSWORD}
      DEBUG : ${DEBUG}
      POSTGRES_DATABASE : django
      POSTGRES_USER : django
      POSTGRES_PASSWORD : ${POSTGRES_PASSWORD}
      POSTGRES_HOST : db

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_ROOT_PASSWORD : ${POSTGRES_ROOT_PASSWORD}
      POSTGRES_DATABASE : django
      POSTGRES_USER : django
      POSTGRES_PASSWORD : ${POSTGRES_PASSWORD}
    volumes:
      - /tmp/app/django_db_socket:/var/run/postgresd
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: {}
  media: {}
  logs: {}

secrets:
  crt:
    file: ./ca.crt
  key:
    file: ./ca.key
  django_secret:
    environment: SECRET_KEY
  email_host_password:
    environment: EMAIL_HOST_PASSWORD