services:
  back:
    build: .
    command: daphne -e ssl:8000:privateKey=ca.key:certKey=ca.crt aquoiquonjoue.asgi:application
    depends_on:
      - db
    ports:
      - 8000:8000
    volumes:
      - /tmp/app/django_db_socket:/run/mysqld
    environment:
      SECRET_KEY : ${SECRET_KEY}
      EMAIL_HOST_PASSWORD : ${EMAIL_HOST_PASSWORD}
      DEBUG : ${DEBUG}
      MYSQL_DATABASE : ${MYSQL_DATABASE}
      MYSQL_USER : ${MYSQL_USER}
      MYSQL_PASSWORD : ${MYSQL_PASSWORD}
      MYSQL_HOST : db

  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD : ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE : ${MYSQL_DATABASE}
      MYSQL_USER : ${MYSQL_USER}
      MYSQL_PASSWORD : ${MYSQL_PASSWORD}
    volumes:
      - /tmp/app/django_db_socket:/var/run/mysqld
      - db_data:/var/lib/mysql

volumes:
  db_data: {}