services:
  back:
    build: .
    image: armitage1/lanrumble-django
    restart: always
    command: ["sh", "-c", "pip install debugpy -t /tmp && python /tmp/debugpy --listen 0.0.0.0:3000 --wait-for-client -m daphne -e ssl:8000:privateKey=ca.key:certKey=ca.crt lanrumble.asgi:application"]
    depends_on:
      - db
    ports:
      - 8000:8000
      - 3000:3000
    volumes:
      - media:/app/jeux/media
      - logs:/var/log/
      - .:/app
    secrets:
      - source: crt
        target: /app/ca.crt
      - source: key
        target: /app/ca.key
    environment:
      SECRET_KEY : ${SECRET_KEY}
      EMAIL_HOST_PASSWORD : ${EMAIL_HOST_PASSWORD}
      DEBUG : ${DEBUG}
      POSTGRES_DATABASE : django
      POSTGRES_USER : django
      POSTGRES_PASSWORD : ${POSTGRES_PASSWORD}
      POSTGRES_HOST : db

  db:
    image: postgres:17-alpine
    restart: always
    environment:
      POSTGRES_ROOT_PASSWORD : ${POSTGRES_ROOT_PASSWORD}
      POSTGRES_DATABASE : django
      POSTGRES_USER : django
      POSTGRES_PASSWORD : ${POSTGRES_PASSWORD}
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: {}
  media: {}
  logs: {}

secrets:
  crt:
    file: ./ca.crt
  key:
    file: ./ca.key
  django_secret:
    environment: SECRET_KEY
  email_host_password:
    environment: EMAIL_HOST_PASSWORD