openapi: 3.0.0
info:
  title: LANRumble API Documentation
  description: Contains all available API endpoints in this codebase
  version: 1.0.0

servers:
  - url: https://127.0.0.1:8000/api

paths:
  /token/:
    post:
      tags:
        - Token management
      summary: Login
      description: API for Login
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Login'
      responses:
        '200':
          $ref: '#/components/responses/Tokens'
        '400':
          $ref: '#/components/responses/400'
        '401':
          $ref: '#/components/responses/401'
        '500':
          description: Internal Server Error
  /token/refresh/:
    post:
      tags:
        - Token management
      summary: Refresh
      description: API for Refresh token
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Refresh'
      responses:
        '200':
          $ref: '#/components/responses/Tokens'
        '400':
          $ref: '#/components/responses/400'
        '401':
          $ref: '#/components/responses/401'
        '500':
          description: Internal Server Error
  /logout/:
    post:
      tags:
        - Token management
      security:
        - Bearer: []
      summary: Logout
      description: Delete user's tokens
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Logout'
      responses:
        '205':
          description: Logout Successfull
        '400':
          $ref: '#/components/responses/400'
        '401':
          $ref: '#/components/responses/401'
        '500':
          description: Internal server error
  /video-game/{id}:
    get:
      tags:
        - Video Game
      summary: Game data
      description: Get game's info like name or player count, etc
      security:
        - Bearer: []
      responses:
        '200':
          description: Game fetched
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Game'
        '404':
          description: Game not found
        '500':
          description: Internal server error
  /video-games:
    get:
      tags:
        - Video Games
      summary: All games
      description: Show all games
      responses:
        '200':
          description: Fetch successfull
          content:
            application/json:
              schema:
                type: array
                items:
                  properties:
                    title:
                      type: string
        '500':
          description: Internal server error
  /user/{userId}/friends:
    get:
      tags:
        - Friends
      summary: User Friend List
      description: All active user's friends
      security:
        - Bearer: []
      parameters:
        - in: path
          name: userId
          required: true
          description: Numeric ID of the user
          schema:
            type: integer
      responses:
        '200':
          description: Fetch successfull
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Friend'
        '401':
          $ref: '#/components/responses/401'
        '500':
          description: Internal server error
  /user/{userId}/video-games:
    get:
      tags:
        - Video Games
      summary: User Id's video games
      description: Show user number id video games
      security:
        - Bearer: []
      parameters:
        - in: path
          name: userId
          required: true
          description: Numeric ID of the user
          schema:
            type: integer
      responses:
        '200':
          description: Fetch successfull
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Game'
        '401':
          $ref: '#/components/responses/401'
        '500':
          description: Internal server error

components:
  securitySchemes:
    Bearer:
      type: apiKey
      name: Authorization
      in: header

  schemas:
    Login:
      properties:
        username:
          type: string
          description: username
        password:
          type: string
          description: user password
    Refresh:
      type: object
      properties:
        refresh:
          type: string
    Logout:
      type: object
      properties:
        refresh_token:
          type: string
    Friend:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
    Game:
      type: object
      properties:
        id:
          type: integer
        title:
          type: string
        pvp:
          type: boolean
        coop:
          type: boolean
        free:
          type: boolean
        hotseat:
          type: integer
        online:
          type: integer

  responses:
    Tokens:
      description: Login of refresh successfull
      content:
        application/json:
          schema:
            type: object
            properties:
              refresh:
                type: string
              access:
                type: string
    Error:
      description: Error response
      content:
        application/json:
          schema:
            type: object
            properties:
              status:
                type: integer
              message:
                type: string
              body:
                type: object
                properties:
                  detail:
                    type: string
                  code:
                    type: string
    401:
      description: Unauthorized
      content:
        application/json:
          schema:
            type: object
            properties:
              detail:
                type: string
              code:
                type: string
    400:
      description: Invalid Fields
      content:
        application/json:
          schema:
            type: object
            additionalProperties: true