swagger: '2.0'
info:
  title: LANRumble API Documentation
  description: Contains all available API endpoints in this codebase
  version: '1.0.0'
  termsOfService: 'http://swagger.io/terms/'
host: 127.0.0.1:8000
basePath: /api/
schemes:
  - https
paths:
  /token/:
    post:
      tags:
        - Token management
      summary: Login
      description: API for Login
      parameters:
        - in: body
          name: body
          description: Login Payload
          required: true
          schema:
            $ref: '#/definitions/Login'
      produces:
        - application/json
      responses:
        '200':
          description: Login Successfully
          schema:
            $ref: '#/definitions/LoginOK'
        '400':
          description: Invalid Fields
        '401':
          description: Login Failed
          schema:
            $ref: '#/definitions/LoginKO'
        '500':
          description: Internal Server Error
  /token/refresh/:
    post:
      tags:
        - Token management
      summary: Refresh
      description: API for Refresh token
      parameters:
        - in: body
          name: body
          description: Refresh Payload
          required: true
          schema:
            $ref: '#/definitions/Refresh'
      produces:
        - application/json
      responses:
        '200':
          description: Refresh Successfull
          schema:
            $ref: '#/definitions/LoginOK'
        '400':
          description: Invalid Fields
        '401':
          description: Refresh Failed
          schema:
            $ref: '#/definitions/RefreshKO'
        '500':
          description: Internal Server Error
  /logout/:
    post:
      tags:
        - Token management
      security:
        - Bearer: []
      summary: Logout
      description: Delete user's tokens
      parameters:
        - in: body
          name: body
          description: Refresh Payload
          required: true
          schema:
            $ref: '#/definitions/Logout'
      produces:
        - application/json
      responses:
        '205':
          description: Logout Successfull
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error

securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
definitions:
  Login:
    properties:
      username:
        type: string
        description: username
      password:
        type: string
        description: user password
  LoginOK:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          refresh:
            type: string
          access:
            type: string
  LoginKO:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          detail:
            type: string
  Refresh:
    type: object
    properties:
      refresh:
        type: string
  RefreshKO:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          detail:
            type: string
          code:
            type: string
  Logout:
    type: object
    properties:
      refresh_token:
        type: string