# Generated by Django 2.2.7 on 2020-02-20 07:42

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import jeux.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Jeu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('coop', models.BooleanField(default=False)),
                ('pvp', models.BooleanField(default=False)),
                ('joueurs_max_hot_seat', models.SmallIntegerField(default=1)),
                ('joueurs_max_online', models.SmallIntegerField(default=0)),
                ('f2p', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Joueur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_body_background', models.CharField(default='#222222', max_length=7)),
                ('color_body_text', models.CharField(default='#ffffff', max_length=7)),
                ('color_nav_background', models.CharField(default='#111111', max_length=7)),
                ('color_nav_link_active', models.CharField(default='#ff0000', max_length=7)),
                ('color_nav_link_hover', models.CharField(default='#ffffff', max_length=7)),
                ('color_nav_link', models.CharField(default='#990000', max_length=7)),
                ('color_nav_text', models.CharField(default='#ffffff', max_length=7)),
                ('background_file', models.FileField(blank=True, upload_to=jeux.models.user_directory_path)),
                ('amis', models.ManyToManyField(blank=True, related_name='_joueur_amis_+', to='jeux.Joueur')),
                ('liste_jeux', models.ManyToManyField(blank=True, to='jeux.Jeu')),
                ('utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Vote_Jeu_Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valeur', models.SmallIntegerField(default=5)),
                ('jeu_concerne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jeux.Jeu')),
                ('joueur_concerne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jeux.Joueur')),
            ],
        ),
        migrations.CreateModel(
            name='TokenResetPassword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=33)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('utilisateur_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Jeu_Societe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('temps_prevu', models.TimeField(default=datetime.time(1, 1))),
                ('joueurs_max', models.SmallIntegerField(default=1)),
                ('joueurs_min', models.SmallIntegerField(default=1)),
                ('complexite', models.SmallIntegerField(default=1)),
                ('possede_par', models.ManyToManyField(blank=True, to='jeux.Joueur')),
            ],
        ),
    ]
