# Generated by Django 2.1.2 on 2018-10-26 17:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Jeu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('coop', models.BooleanField(default=False)),
                ('pvp', models.BooleanField(default=False)),
                ('joueurs_max_hot_seat', models.SmallIntegerField(default=0)),
                ('joueurs_max_online', models.SmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Joueur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amis', models.ManyToManyField(related_name='_joueur_amis_+', to='jeux.Joueur')),
                ('list_jeux', models.ManyToManyField(to='jeux.Jeu')),
                ('utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
