# Generated by Django 2.1.2 on 2018-10-26 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jeux', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joueur',
            name='amis',
            field=models.ManyToManyField(blank=True, related_name='_joueur_amis_+', to='jeux.Joueur'),
        ),
        migrations.AlterField(
            model_name='joueur',
            name='list_jeux',
            field=models.ManyToManyField(blank=True, to='jeux.Jeu'),
        ),
    ]
