# Generated by Django 5.0.6 on 2024-06-28 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jeux', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joueur',
            name='amis',
            field=models.ManyToManyField(blank=True, to='jeux.joueur'),
        ),
    ]
