# Generated by Django 4.2.1 on 2024-10-09 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jeux', '0002_alter_joueur_amis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tokenresetpassword',
            name='token',
            field=models.CharField(max_length=100),
        ),
    ]
