# Generated by Django 2.1.2 on 2018-10-31 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jeux', '0003_auto_20181026_1801'),
    ]

    operations = [
        migrations.AddField(
            model_name='jeu',
            name='f2p',
            field=models.BooleanField(default=False),
        ),
    ]
