# Generated by Django 4.2.15 on 2024-10-18 08:22

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jeux', '0004_rename_jeu_videogame'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Jeu_Societe',
            new_name='Boardgame',
        ),
        migrations.RenameModel(
            old_name='Joueur',
            new_name='Player',
        ),
        migrations.RenameModel(
            old_name='Vote_Jeu_Video',
            new_name='VideogameRating',
        ),
    ]
