# Generated by Django 2.1.2 on 2018-11-02 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jeux', '0004_jeu_f2p'),
    ]

    operations = [
        migrations.AddField(
            model_name='joueur',
            name='color_body_background',
            field=models.CharField(default='222', max_length=6),
        ),
        migrations.AddField(
            model_name='joueur',
            name='color_body_text',
            field=models.CharField(default='fff', max_length=6),
        ),
        migrations.AddField(
            model_name='joueur',
            name='color_nav_background',
            field=models.CharField(default='111', max_length=6),
        ),
        migrations.AddField(
            model_name='joueur',
            name='color_nav_link',
            field=models.CharField(default='900', max_length=6),
        ),
        migrations.AddField(
            model_name='joueur',
            name='color_nav_link_active',
            field=models.CharField(default='f00', max_length=6),
        ),
        migrations.AddField(
            model_name='joueur',
            name='color_nav_link_hover',
            field=models.CharField(default='fff', max_length=6),
        ),
        migrations.AddField(
            model_name='joueur',
            name='color_nav_text',
            field=models.CharField(default='fff', max_length=6),
        ),
    ]
