# Generated by Django 2.1.2 on 2018-11-02 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jeux', '0005_auto_20181102_0228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jeu',
            name='joueurs_max_hot_seat',
            field=models.SmallIntegerField(default=1),
        ),
    ]
