# Generated by Django 2.1.2 on 2018-11-04 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jeux', '0006_auto_20181102_2044'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jeu_Societe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('temps_prevu', models.SmallIntegerField(default=1)),
                ('joueurs_max', models.SmallIntegerField(default=1)),
                ('joueurs_min', models.SmallIntegerField(default=1)),
                ('complexite', models.CharField(max_length=50)),
                ('possede_par', models.ManyToManyField(blank=True, to='jeux.Joueur')),
            ],
        ),
    ]
