# Generated by Django 4.2.15 on 2024-10-18 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jeux', '0007_alter_videogamerating_player_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='utilisateur',
            new_name='user',
        ),
    ]
