# Generated by Django 2.1.7 on 2019-02-24 19:26

import datetime
from django.db import migrations, models
import django.db.models.deletion
import jeux.models


class Migration(migrations.Migration):

    dependencies = [
        ('jeux', '0007_jeu_societe'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vote_Jeu_Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valeur', models.SmallIntegerField(default=5)),
                ('jeu_concerne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jeux.Jeu')),
            ],
        ),
        migrations.AddField(
            model_name='joueur',
            name='background_file',
            field=models.FileField(blank=True, upload_to=jeux.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='jeu_societe',
            name='complexite',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='jeu_societe',
            name='temps_prevu',
            field=models.TimeField(default=datetime.time(1, 1)),
        ),
        migrations.AlterField(
            model_name='joueur',
            name='color_body_background',
            field=models.CharField(default='#222222', max_length=7),
        ),
        migrations.AlterField(
            model_name='joueur',
            name='color_body_text',
            field=models.CharField(default='#ffffff', max_length=7),
        ),
        migrations.AlterField(
            model_name='joueur',
            name='color_nav_background',
            field=models.CharField(default='#111111', max_length=7),
        ),
        migrations.AlterField(
            model_name='joueur',
            name='color_nav_link',
            field=models.CharField(default='#990000', max_length=7),
        ),
        migrations.AlterField(
            model_name='joueur',
            name='color_nav_link_active',
            field=models.CharField(default='#ff0000', max_length=7),
        ),
        migrations.AlterField(
            model_name='joueur',
            name='color_nav_link_hover',
            field=models.CharField(default='#ffffff', max_length=7),
        ),
        migrations.AlterField(
            model_name='joueur',
            name='color_nav_text',
            field=models.CharField(default='#ffffff', max_length=7),
        ),
        migrations.AddField(
            model_name='vote_jeu_video',
            name='joueur_concerne',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jeux.Joueur'),
        ),
    ]
