# Generated by Django 2.2.7 on 2020-02-20 02:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jeux', '0008_auto_20190224_1926'),
    ]

    operations = [
        migrations.CreateModel(
            name='TokenResetPassword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=33)),
                ('created', models.DateField(auto_now_add=True)),
                ('utilisateur_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
