# Generated by Django 2.2.7 on 2020-02-20 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jeux', '0009_tokenresetpassword'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tokenresetpassword',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
